# Generated by Django 5.1.6 on 2025-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="year",
        ),
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="hobbies",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="major",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
