import { MatchData } from "@/types/types";

export const currentMatches: MatchData[] = [
  {
    name: "Emma Johnson",
    username: "emma_j",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma@example.com",
    bio: "Psychology major who loves hiking and photography.",
    age: 20,
    major: "Psychology",
    year: "Junior",
    interests: ["Hiking", "Photography", "Reading", "Yoga"],
    photos: [
      "https://i.pravatar.cc/300?img=5",
      "https://i.pravatar.cc/300?img=15",
      "https://i.pravatar.cc/300?img=25",
    ],
    dpAgeRange: [18, 25],
    dpDistance: 15,
    dpShowMe: "everyone",
    dpInterests: [],
    dpMajors: [],
    notiNewMatches: true,
    notiMessages: true,
    notiAppUpdates: true,
    notiEmailNotifications: true,
    priProfileVisibility: "public",
    priShowOnlineStatus: true,
    priShowLastActive: true,
    priAllowTagging: true,
    lastActive: "2 hours ago",
  },
  {
    name: "Michael Chen",
    username: "mike_c",
    avatar: "https://i.pravatar.cc/150?img=11",
    email: "michael@example.com",
    bio: "Computer Science student who enjoys basketball and coding.",
    age: 22,
    major: "Computer Science",
    year: "Senior",
    interests: ["Coding", "Basketball", "Gaming", "Movies"],
    photos: [
      "https://i.pravatar.cc/300?img=11",
      "https://i.pravatar.cc/300?img=21",
      "https://i.pravatar.cc/300?img=31",
    ],
    dpAgeRange: [19, 26],
    dpDistance: 20,
    dpShowMe: "everyone",
    dpInterests: [],
    dpMajors: [],
    notiNewMatches: true,
    notiMessages: true,
    notiAppUpdates: false,
    notiEmailNotifications: true,
    priProfileVisibility: "public",
    priShowOnlineStatus: true,
    priShowLastActive: true,
    priAllowTagging: false,
    lastActive: "5 minutes ago",
  },
  {
    name: "Sophia Rodriguez",
    username: "sophia_r",
    avatar: "https://i.pravatar.cc/150?img=9",
    email: "sophia@example.com",
    bio: "Art major with a passion for painting and music.",
    age: 21,
    major: "Art",
    year: "Junior",
    interests: ["Art", "Music", "Dancing", "Traveling"],
    photos: [
      "https://i.pravatar.cc/300?img=9",
      "https://i.pravatar.cc/300?img=19",
      "https://i.pravatar.cc/300?img=29",
    ],
    dpAgeRange: [20, 28],
    dpDistance: 25,
    dpShowMe: "everyone",
    dpInterests: [],
    dpMajors: [],
    notiNewMatches: true,
    notiMessages: true,
    notiAppUpdates: true,
    notiEmailNotifications: false,
    priProfileVisibility: "public",
    priShowOnlineStatus: false,
    priShowLastActive: true,
    priAllowTagging: true,
    lastActive: "1 day ago",
  },
];

export const potentialMatches: MatchData[] = [
  {
    name: "David Wilson",
    username: "david_w",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "david@example.com",
    bio: "Engineering student who loves hiking and playing guitar.",
    age: 23,
    major: "Engineering",
    year: "Senior",
    interests: ["Hiking", "Music", "Gaming", "Cooking"],
    photos: [
      "https://i.pravatar.cc/300?img=12",
      "https://i.pravatar.cc/300?img=22",
      "https://i.pravatar.cc/300?img=32",
    ],
    dpAgeRange: [20, 27],
    dpDistance: 15,
    dpShowMe: "everyone",
    dpInterests: [],
    dpMajors: [],
    notiNewMatches: true,
    notiMessages: true,
    notiAppUpdates: false,
    notiEmailNotifications: true,
    priProfileVisibility: "public",
    priShowOnlineStatus: true,
    priShowLastActive: true,
    priAllowTagging: true,
    matchPercentage: 92,
  },
  {
    name: "Olivia Taylor",
    username: "olivia_t",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "olivia@example.com",
    bio: "Biology major who enjoys reading and swimming.",
    age: 20,
    major: "Biology",
    year: "Sophomore",
    interests: ["Reading", "Swimming", "Cooking", "Movies"],
    photos: [
      "https://i.pravatar.cc/300?img=8",
      "https://i.pravatar.cc/300?img=18",
      "https://i.pravatar.cc/300?img=28",
    ],
    dpAgeRange: [19, 25],
    dpDistance: 10,
    dpShowMe: "everyone",
    dpInterests: [],
    dpMajors: [],
    notiNewMatches: true,
    notiMessages: true,
    notiAppUpdates: true,
    notiEmailNotifications: true,
    priProfileVisibility: "public",
    priShowOnlineStatus: true,
    priShowLastActive: false,
    priAllowTagging: false,
    matchPercentage: 85,
  },
  {
    name: "James Brown",
    username: "james_b",
    avatar: "https://i.pravatar.cc/150?img=13",
    email: "james@example.com",
    bio: "Mathematics student with a love for chess and basketball.",
    age: 22,
    major: "Mathematics",
    year: "Junior",
    interests: ["Basketball", "Chess", "Coding", "Reading"],
    photos: [
      "https://i.pravatar.cc/300?img=13",
      "https://i.pravatar.cc/300?img=23",
      "https://i.pravatar.cc/300?img=33",
    ],
    dpAgeRange: [18, 24],
    dpDistance: 20,
    dpShowMe: "everyone",
    dpInterests: [],
    dpMajors: [],
    notiNewMatches: true,
    notiMessages: false,
    notiAppUpdates: false,
    notiEmailNotifications: true,
    priProfileVisibility: "public",
    priShowOnlineStatus: false,
    priShowLastActive: true,
    priAllowTagging: true,
    matchPercentage: 78,
  },
  {
    name: "Ava Martinez",
    username: "ava_m",
    avatar: "https://i.pravatar.cc/150?img=7",
    email: "ava@example.com",
    bio: "Psychology student interested in art therapy and hiking.",
    age: 21,
    major: "Psychology",
    year: "Junior",
    interests: ["Art", "Hiking", "Yoga", "Traveling"],
    photos: [
      "https://i.pravatar.cc/300?img=7",
      "https://i.pravatar.cc/300?img=17",
      "https://i.pravatar.cc/300?img=27",
    ],
    dpAgeRange: [20, 26],
    dpDistance: 15,
    dpShowMe: "everyone",
    dpInterests: [],
    dpMajors: [],
    notiNewMatches: true,
    notiMessages: true,
    notiAppUpdates: true,
    notiEmailNotifications: false,
    priProfileVisibility: "public",
    priShowOnlineStatus: true,
    priShowLastActive: true,
    priAllowTagging: false,
    matchPercentage: 73,
  },
];
