# Generated by Django 5.1.6 on 2025-03-12 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.ManyToManyField(blank=True, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('matched', models.ManyToManyField(blank=True, related_name='matched_with', to=settings.AUTH_USER_MODEL)),
                ('rejected', models.ManyToManyField(blank=True, related_name='rejected_by', to=settings.AUTH_USER_MODEL)),
                ('super_liked', models.ManyToManyField(blank=True, related_name='super_liked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='matching_ma_user_id_b27111_idx')],
            },
        ),
    ]
