# Generated by Django 5.1.6 on 2025-03-11 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.CreateModel(
            name='MatchInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('match', 'Match')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddIndex(
            model_name='matchinteraction',
            index=models.Index(fields=['user1', 'interaction_type'], name='matching_ma_user1_i_963fad_idx'),
        ),
        migrations.AddIndex(
            model_name='matchinteraction',
            index=models.Index(fields=['user2', 'interaction_type'], name='matching_ma_user2_i_ea2548_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchinteraction',
            unique_together={('user1', 'user2', 'interaction_type')},
        ),
    ]
