# Generated by Django 5.1.6 on 2025-03-12 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="match",
            name="approved",
            field=models.ManyToManyField(
                blank=True, related_name="approved_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="matched",
            field=models.ManyToManyField(
                blank=True, related_name="matched_with", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="rejected",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="super_liked",
            field=models.ManyToManyField(
                blank=True, related_name="super_liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="user",
            field=models.OneToOneField(
                default=700,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="match",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="user2",
        ),
    ]
