# Generated by Django 5.1.6 on 2025-03-11 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_match_unique_together_remove_match_user1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.ManyToManyField(blank=True, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('matched', models.ManyToManyField(blank=True, related_name='matched_with', to=settings.AUTH_USER_MODEL)),
                ('rejected', models.ManyToManyField(blank=True, related_name='rejected_by', to=settings.AUTH_USER_MODEL)),
                ('super_liked', models.ManyToManyField(blank=True, related_name='super_liked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MatchInteraction',
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user'], name='matching_ma_user_id_b27111_idx'),
        ),
    ]
