# Generated by Django 5.1.6 on 2025-03-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_match_delete_matchinteraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='updated_at',
        ),
    ]
